### ISSUE TITLE
Please target Netstandard 2.0 instead of Netcoreapp 2.0

### ISSUE THREAD

**Issue by kodfodrasz** [polischuk/SlugGenerator#2]
Hi!

I'm using the library from a netstandard 2.0 library and I get warnings.
I had to make the class library project a Netcoreapp-2.1 project to be sure to avoid problems.

Could you please retarget the project to netstandard 2.0? That way for framework 4.7 you would not need a separate project.

Thanks!

**Comment by polischuk** [comment]
Hi, Please install the new version 
`Install-Package SlugGenerator -Version 2.0.2`

Version 2.0.2 Contains:
 .net 4.5 version
.net standart 2.0 version
asp.net core 2.0 version
